version: '3.7'

services:
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_DBNAME=guidly_backend
      - POSTGRES_USER=guidly_backend
      - POSTGRES_PASSWORD=guidly_backend
      - POSTGRES_PORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: guidly_backend
    command: bash -c "python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data:
